### ISSUE TITLE
Provide the functionality of cloning an existing campaign

### ISSUE THREAD

**Issue by fmdcerveira** [ucx-code/ucXception#10]
To avoid the repetitive process of filling out a campaign, the user should be able to create a new campaign using an existing campaign as the basis (i.e. clone it). The idea is that the fields required to create a new campaign would be pre-filled using the values of the basis campaign. The user could then edit the fields and, when ready, create and launch the campaign.

**Comment by fmdcerveira** [comment]
Consider starting by Issue #13

**Comment by HenriqueDiz** [comment]
just gonna close to take print for ppt
