### ISSUE TITLE
Golden Runs Otimization

### ISSUE THREAD

**Issue by HenriqueDiz** [ucx-code/ucXception#14]
Create an otimization towards a more friendly user interface so that the user can easily  run a Golden Run without having to follow every step of a normal test.
or
Suggestion of times that the user can put on 'f_min', 'f_max' and 'watch_dog' when going for fault injection runs

**Comment by fmdcerveira** [comment]
We see two possible paths with varying degrees of complexity:
1- Add text to help the user better understand each parameter.
2- Create a system to suggest values for fi_min, fi_max, etc. based on the workload application and its input (implies that the system will run 3 or 4 times the application and suggest values).

**Comment by HenriqueDiz** [comment]
The second path was chosen: a button was created that launches a process with the app_input, the file, and the campaign type specified by the user (running with a fixed watchdog duration of 50,000 and with 5 total runs). It then sends the f_min, f_max, and watchdog_dur values suggested.
