### ISSUE TITLE
Do not allow repeated hosts for the same role

### ISSUE THREAD

**Issue by fmdcerveira** [ucx-code/ucXception#15]
![Screenshot from 2024-02-14 15-43-19](https://github.com/ucx-code/ucXception/assets/92426/9193baee-03c1-450d-b564-1de523183a89)

**Comment by HenriqueDiz** [comment]
Wrote a function to manage hosts: if a host doesn't have 'campaign target' and doesn't have 'Fault injector target', it gets deleted.
