### ISSUE TITLE
Allow campaigns to be archived

### ISSUE THREAD

**Issue by fmdcerveira** [ucx-code/ucXception#5]
This is an idea of a possible improvement. A user may be able to archive various finished campaigns.

**Comment by HenriqueDiz** [comment]
To implement this functionality, a column was added to the SQL table "campaign" to indicate whether the campaign is archived. It is set to true if the campaign is archived and false if it is not (by default, it is set to false). The user can then also unarchive it if they desire to do so.

**Comment by HenriqueDiz** [comment]
I also took the opportunity to change the message displayed depending on the case: whether the campaigns are archived or not, and whether the search was successful or not (instead of always showing "No Campaigns Created").
