### ISSUE TITLE
Sort campaigns

### ISSUE THREAD

**Issue by fmdcerveira** [ucx-code/ucXception#7]
It should be possible to sort the campaigns by Start Date and Execution.

**Comment by fmdcerveira** [comment]
Instead of Execution, we will sort by Campaign Name

**Comment by HenriqueDiz** [comment]
Implemented 2 "CformSelect" so the user can choose how he wants to sort the table by Campaign name or Start Date and the way  of the sort : for Campaign Name can be A-Z or Z-A and for Start Date can be Oldest to Newest or Newest to Oldest

**Comment by HenriqueDiz** [comment]
Also added search by start date instead of execution name
