### ISSUE TITLE
Show information about the logged in user

### ISSUE THREAD

**Issue by fmdcerveira** [ucx-code/ucXception#8]
Currently it is impossible for the user to know with which account he is logged in.
When the user clicks in the rightmost topmost icon (see figure), it should show there its name and email.

![Screenshot from 2024-01-12 16-13-52](https://github.com/ucx-code/ucXception/assets/92426/3a089eb2-262c-4a9f-a0ef-0fa00d97fb59)

**Comment by IRON5K** [comment]
Uploaded information through local storage (Tried to use useState but we reload the page the information would be gone)
